docs: project philosophy #445
vitejs/docs-es pull request #457
Opened 2023-07-03 17:14 UTC by marcterradas

Resolves #445

2023-07-04 01:56 UTC, mrcego requested changes

2023-07-04 01:56 UTC, mrcego commented on docs/.vitepress/config.ts
> +              text: 'Philosophy',
En español por favor.

2023-07-04 01:56 UTC, mrcego commented on docs/guide/philosophy.md
> +## Núcleo Extensible y Liviano
Núcleo extensible y liviano

2023-07-04 01:56 UTC, mrcego commented on docs/guide/philosophy.md
> +Vite no tiene la intención de cubrir todos los casos de uso para todos los usuarios. Vite tiene como objetivo soportar los patrones más comunes para construir aplicaciones web fuera de la caja, pero
Las funcionalidades que se pueden...

2023-07-04 01:56 UTC, mrcego commented on docs/guide/philosophy.md
> +Vite ofrece características con opiniones que promueven la escritura de código moderno. Por ejemplo:
Vite ofrece funcionalidades pragmáticas...

2023-07-04 01:56 UTC, mrcego commented on docs/guide/philosophy.md
> +Al agregar nuevas características, se siguen estos patrones para crear una API a prueba de futuro, que no siempre es compatible con otras herramientas de compilación.
Al agregar nuevas funcionalidades...

2023-07-04 01:56 UTC, mrcego commented on docs/guide/philosophy.md
> +## Enfoque Pragmático hacia el Rendimiento
Enfoque pragmático hacia el rendimiento

2023-07-04 01:56 UTC, mrcego commented on docs/guide/philosophy.md
> +Vite se ha centrado en el rendimiento desde sus [orígenes](./why.md). Su arquitectura del servidor de desarrollo permite una actualización en caliente (HMR) que se mantiene rápida a medida que los pr
Su arquitectura de servidor de desarrollo...

... utilizando nuevas bibliotecas a medida que aparezcan...

2023-07-04 01:56 UTC, mrcego commented on docs/guide/philosophy.md
> +## Construyendo Marcos sobre Vite
Construyendo marcos de trabajo sobre Vite

2023-07-04 01:56 UTC, mrcego commented on docs/guide/philosophy.md
> +Aunque Vite se puede utilizar directamente por los usuarios, brilla como una herramienta para crear frameworks. El núcleo de Vite es independiente del framework, pero existen complementos pulidos par
_Framework_ es español por favor.

Cuando hay demasiadas repeticiones, puedes usar la palabra _marco_ para simplicidad. Está a tu opción.

2023-07-04 01:56 UTC, mrcego commented on docs/guide/philosophy.md
> +Aunque Vite se puede utilizar directamente por los usuarios, brilla como una herramienta para crear frameworks. El núcleo de Vite es independiente del framework, pero existen complementos pulidos par
... utilizar las funcionalidades de Vite...

... pero que son fundamentales para construir...

2023-07-04 01:56 UTC, mrcego commented on docs/guide/philosophy.md
> +## Un Ecosistema Activo
Un ecosistema activo

2023-07-04 01:56 UTC, mrcego commented on docs/guide/philosophy.md
> +La evolución de Vite es una cooperación entre los mantenedores de frameworks y plugins, los usuarios y el equipo de Vite. Fomentamos la participación activa en el desarrollo del núcleo de Vite una ve
... que utilizan Vite en las solicitudes de cambios seleccionadas...

2023-07-04 01:56 UTC, mrcego commented on docs/guide/philosophy.md
> +Aunque Vite se puede utilizar directamente por los usuarios, brilla como una herramienta para crear frameworks. El núcleo de Vite es independiente del framework, pero existen complementos pulidos par
Interfaz de usuario (IU)

2023-07-04 18:11 UTC, mrcego requested changes

2023-07-04 18:11 UTC, mrcego commented on docs/guide/philosophy.md
> +## Construyendo frameworks de trabajo sobre Vite
frameworks o marcos de trabajo, cual de los dos?

2023-07-04 18:20 UTC, marcterradas commented on docs/guide/philosophy.md
> +## Construyendo frameworks de trabajo sobre Vite
te parece mejor framework? creo que se va a entender mejor

2023-07-05 15:08 UTC, mrcego commented on docs/guide/philosophy.md
> +## Construyendo frameworks de trabajo sobre Vite
Me parece perfecto.

2023-07-05 15:17 UTC, mrcego approved these changes

2023-07-06 13:46 UTC, merged