docs: add comment in create project guide
vitejs/docs-es pull request #678
Opened 2024-05-28 16:20 UTC by Franqsanz

Problem solved: #674.

2024-05-28 23:20 UTC, mrcego requested changes

2024-05-28 23:20 UTC, mrcego commented on docs/guide/index.md
> +Puede utilizar `.` para el nombre del proyecto para andamiar en el directorio actual.
Usar tuteo por favor. "Puedes...".

¿Andamiar? ¿Puedes ser un sinónimo?

2024-05-28 23:40 UTC, Franqsanz commented on docs/guide/index.md
> +Puede utilizar `.` para el nombre del proyecto para andamiar en el directorio actual.
Hola, de esta manera te parece bien? 

"Puedes usar `.` como nombre del proyecto para generar la estructura en el directorio actual"

2024-05-29 00:33 UTC, mrcego commented on docs/guide/index.md
> +Puede utilizar `.` para el nombre del proyecto para andamiar en el directorio actual.
Adecuado. Muchas gracias.

2024-05-29 03:37 UTC, mrcego approved these changes

2024-05-29 03:37 UTC, mrcego commented
Gracias 😀

2024-05-29 11:20 UTC, Franqsanz reviewed
Resuelto.

2024-05-29 17:14 UTC, mrcego commented
> No logro entender por qué los checks no pasan

Prueba a hacer `pnpm i` y sube el package-lock.

2024-05-29 17:36 UTC, Franqsanz commented
Resuelto, actualice la versión de 6.0 a 9.0.

2024-05-29 19:28 UTC, merged